# Generated by Django 4.0.6 on 2022-08-01 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassNames', models.CharField(max_length=255, unique=True)),
                ('Teacher', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClassMembersDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentReg', models.CharField(default=None, max_length=255)),
                ('ClassLevelName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classManagement.classlist')),
            ],
        ),
    ]
